name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# Make sure CI fails on all warnings
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable && rustup default stable
      - name: "Run rustfmt"
        run: cargo fmt --all --check
      - name: "Run clippy"
        run: cargo clippy --workspace --all-targets --all-features
  
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: rustup update stable && rustup default stable
    - name: "Run tests"
      run: cargo test
