name: Rust Docs CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: rustup update stable && rustup default stable

    - name: Generate Documentation
      run: cargo doc --no-deps

    - run: echo '<meta http-equiv=refresh content=0;url=YOURLIBNAME/index.html>' > ./target/doc/index.html 

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/doc
        user_name: GitHub Actions
        user_email: actions@github.com
        commit_message: "Deploy docs to GitHub Pages"
